INSERT INTO funeralParlour VALUES
('NULL','Uitvaartcentrum Duin',0,NULL),
    ('NULL','Yarden',1,NULL),
    ('NULL','Dunweg',1,NULL),
    ('NULL','Bennis Uitvaart',0,NULL),
    ('NULL','Dela',1,'zaterdag niet mogelijk werken ook met bloemenkas.'),
    ('NULL','Yardenhuis van Rotterdam',0,NULL),
    ('NULL','Uitvaartcentrum Leidschendam-Voorburg ',0,NULL),
    ('NULL','Beukenhof',0,NULL),
    ('NULL','Uitvaartcentrum Kranenburg',0,'bloemenkast met code'),
    ('NULL','Uitvaartzorg Boerhaavelaan',1,'Tussen 9,00 en 17,00'),
    ('NULL','Draagt Elkanders Lasten ',1,NULL),
    ('NULL','Yardenhuis van Schagen',1,'afgeven bij administratie aan de achterkant'),
    ('NULL','Assosiatie Uitvaartverzorging',1,'door de weeks tussen 9 en 16 uur iemand aanwezig om te tekenen. Zaterdag in de kas leggen. Achter het pand'),
    ('NULL','De nieuwe Ooster',1,'Ook op zaterdag is voor hun een normale werkdag.'),
    ('NULL','J Henning ',0,'Bloemenkast'),
    ('NULL','Het Afscheidshuys',0,'Bloemenkast'),
    ('NULL','Waerdse Landen',1,'Van half 9 tot 17:00 uur'),
    ('NULL','Hofwijk',1,'Alleen op de dag van de uitvaart!! '),
    ('NULL','Rijtackers',1,'kantoortijden'),
    ('NULL','Dela Roosendaal',1,NULL),
    ('NULL','''t kruispunt',0,'afspraak maken'),
    ('NULL','Rouwcentrum de Palm',0,'bloemenkast en formulier'),
    ('NULL','Monuta Ogier',0,'Bloemenkast'),
    ('NULL','Uitvaartcentrum zuid',1,'kantoortijden'),
    ('NULL','boschhuizen Dela',0,'bloemenkast en formulier'),
    ('NULL','Begraafplaats Essenhof',0,'bloemenkast en formulier'),
    ('NULL','Eeken',0,'Beperkte tijden + afspraak maken.'),
    ('NULL','Uitvaartcentrum Watergraafsmeer van PC Uitvaart ',0,'Beperkte tijden'),
    ('NULL','Monuta wilco Leukenhaus',0,'doorgeven aan duivenvoorde'),
    ('NULL','Begraafplaats Holy',0,NULL),
    ('NULL','Goetzee Dela',0,'bloemenkast met lijst'),
    ('NULL','Monuta Uitvaartcentrum Amersfoort',0,'bloemenkast en hek met code'),
    ('NULL','Uitvaartcentrum Bruijns Oosterhout ',0,'leveranciers ingang aan de achterkant'),
    ('NULL','Boerderij Moskowa ',0,'bloemenkast en code'),
    ('NULL','Den en Rust',0,'niet altijd iemand aanwezig om te helpen met bloemen'),
    ('NULL','Dela',0,'bloemenkast en formulier'),
    ('NULL','Monuta Memoriam',0,'bloemenkast code 1999'),
    ('NULL','Waalstede',1,'kantoortijden'),
    ('NULL','Westerhuis',0,NULL),
    ('NULL','Westgaarde',1,NULL),
    ('NULL','Boskamp',1,'Tot 16,30'),
    ('NULL','Ockenburg',0,NULL),
    ('NULL','DELU',0,NULL),
    ('NULL','The Funeral Drechtstreek & Timmers ',0,'bellen voor een code'),
    ('NULL','Dela',1,'Tussen 9,00 en 17,00'),
    ('NULL','monuta ',0,NULL),
    ('NULL','domstede',1,'Voor 16.00'),
    ('NULL','Monuta Uitvaartcentrum Almere',0,'Bloemenkast'),
    ('NULL','Van Vuure',0,'Bloemenkast'),
    ('NULL','Zaanstad',1,'zaterdag tot 11,00'),
    ('NULL','crematorium jonkerbos ',1,'kantoortijden ma tm vrij'),
    ('NULL','Crematorium en Uitvaartcentrum Hoorn',1,NULL),
    ('NULL','Bennis Uitvaart',0,'bloemenkast met code'),
    ('NULL','Henning',0,NULL),
    ('NULL','Uitvaartcentrum Dekker',0,NULL),
    ('NULL','Cuvo Haagse duinen',0,NULL),
    ('NULL','monuta ',0,NULL),
    ('NULL','van der stappen',1,'kantoortijden en zaterdag tot 16.00'),
    ('NULL','de linge',0,NULL),
    ('NULL','Achterberg Uitvaartcentrum',1,'9:30 – 16:30'),
    ('NULL','hart van berkelland',0,'bloemenkast achterzijde pand'),
    ('NULL','VREDEHOF',0,'bloemenkamer'),
    ('NULL','De Ommering',1,'Tussen 9:00 uur en 16:00'),
    ('NULL','vd weerd',0,NULL),
    ('NULL','RGU DELA',0,NULL),
    ('NULL','Monuta van der Togt ',0,NULL),
    ('NULL','Yarden van Lelystad',1,' Ma – za '),
    ('NULL','dela',1,NULL),
    ('NULL','de haan vd kamp dela',0,NULL),
    ('NULL','Noorderveld',1,NULL),
    ('NULL','Tussen de Bergen',1,'maar toch wel bellen voor de zekerheid'),
    ('NULL','Afscheidshuis de Uytvaert ',0,NULL),
    ('NULL','Uitvaartcentrum Leijsenakkers DELA Oosterhout',0,NULL),
    ('NULL','Begrafenisonderneming G Leeuw ',0,NULL),
    ('NULL','Crematorium Maaslanden ',0,NULL),
    ('NULL','monuta ',1,NULL),
    ('NULL','monuta',0,NULL),
    ('NULL','Haarlemmermeer',0,'soms wel soms niet, dus bellen'),
    ('NULL','monuta ',0,NULL),
    ('NULL','Waaijer',1,NULL),
    ('NULL','Hoeksche Waard',1,'Altijd even bellen van te voren');
