INSERT INTO locations VALUES
    ('NULL','van Maerlandstraat ','4','Alkmaar'),
    ('NULL','Overkrocht','20','Alkmaar'),
    ('NULL','Achterweg','40','Hoofddorp'),
    ('NULL','Dorpsstraat ','18','Wormer'),
    ('NULL','Karel Boddenweg','3','Tilburg'),
    ('NULL','Maeterlinckweg','101','Rotterdam'),
    ('NULL','Strandwal','1','Leidschendam '),
    ('NULL','Burg van Haarenlaan','1450','Schiedam'),
    ('NULL','Kranenburgweg','3','Zwolle'),
    ('NULL','Boerhaavelaan','19','Groningen'),
    ('NULL','De Noord','6','Urk'),
    ('NULL','Haringhuizerweg','3','Schagen'),
    ('NULL','Jan van Scorelstraat','9','Zaandam'),
    ('NULL','Kruislaan','126','Amsterdam'),
    ('NULL','Bautersemstraat','1','S-Gravenhage'),
    ('NULL','Soerenseweg','71','Apeldoorn'),
    ('NULL','Krusemanlaan','5','Heerhugowaard'),
    ('NULL','Delftweg','230','Rotterdam'),
    ('NULL','Anthony Fokkerweg','150','Eindhoven'),
    ('NULL','Robijndijk','215','Roosendaal'),
    ('NULL','Beatrixstraat','13','Vlagtwedde'),
    ('NULL','Palmentuin','73','rotterdam'),
    ('NULL','Buytenparklaan','2','Zoetermeer'),
    ('NULL','Fred. Roeskestraat','91','Amsterdam'),
    ('NULL','Spurkterdijk','40','Oostrum'),
    ('NULL','Nassauweg','200','Dordrecht'),
    ('NULL','Laan van Meerestein','10','Beverwijk'),
    ('NULL','Zaaiersweg','2','Amsterdam'),
    ('NULL','Mr HF de Boerlaan','63a','Deventer'),
    ('NULL','Olmendreef','150','Vlaardingen'),
    ('NULL','Boezemsingel','35','Rotterdam'),
    ('NULL','Ringweg-Dorrestein','9','Amersfoort'),
    ('NULL','Florijnstraat','60','Oosterhout '),
    ('NULL','Apeldoornseweg','103','Arnhem '),
    ('NULL','Frans Halslaan','27','Bilthoven '),
    ('NULL','Weg langs de Begraafplaatsen','5','Arnhem '),
    ('NULL','Langenhorst','100','Rotterdam'),
    ('NULL','Staddijk','130','nijmegen'),
    ('NULL','Espelerlaan','69a','Emmeloord'),
    ('NULL','Ookmeerweg','275','Amsterdam'),
    ('NULL','BOSKAMP','5','assen'),
    ('NULL','Ockenburg','21','Den Haag'),
    ('NULL','Het Haagje','169','Hoogeveen'),
    ('NULL','Jan Steenstraat','71','Sliedrecht '),
    ('NULL','Rompertsebaan','48','Den bosch'),
    ('NULL','aalberseplein','1','gouda'),
    ('NULL','Proostwetering','8','utrecht'),
    ('NULL','Kalenderweg','3','Almere'),
    ('NULL','Melkpad','23','Hilversum'),
    ('NULL','Wibautstraat','282','Zaandam'),
    ('NULL','weg door jonkerbos','51','nijmegen'),
    ('NULL','Berkhouterweg','26','Hoorn 1624 NT'),
    ('NULL','Padlaan','1','Krommenie'),
    ('NULL','Bautersemstraat','1','Den Haag'),
    ('NULL','oostelijke randweg ','30','Zuid scharwoude'),
    ('NULL','Wijndaelersingel','1','Den Haag'),
    ('NULL','Veenhuizerweg','143','Apeldoorn'),
    ('NULL','spaarpot oost','2','geldrop'),
    ('NULL','medelsestraat oost','20','Tiel'),
    ('NULL','Wolter Heukelslaan','50-51','utrecht'),
    ('NULL','Groenloseweg','2','haarlo'),
    ('NULL','wethouder beverstraat','104','enschede'),
    ('NULL','Oprelseweg','3','Spijkenisse'),
    ('NULL','Schaapsweg','77-79','ede'),
    ('NULL','Sammersweg','4','Rijswijk'),
    ('NULL','Rodelaan','60','Voorburg'),
    ('NULL','Oostrandreef','1','Lelystad'),
    ('NULL','Tuinzigtlaan','41','breda'),
    ('NULL','Mozartweg','58','Amersfoort'),
    ('NULL','Structuurbaan','1','Nieuwegein'),
    ('NULL','Olympiaalaan','2','Roermond'),
    ('NULL','Welgelegen','1a','Rozenburg'),
    ('NULL','Veerseweg','40','Oosterhout '),
    ('NULL','Wilhelminastraat','68','Fijnaart'),
    ('NULL','Abt van Engelenlaan','1','Nieuwkuijk '),
    ('NULL','Karel Boddenweg','7','Tilburg '),
    ('NULL','Weerdingerstraat','201','emmen'),
    ('NULL','Hoofdweg','1100','Nieuw-Vennep'),
    ('NULL','Nijverheidsweg','4','ulft'),
    ('NULL','Olmendreef','160','Vlaardingen'),
    ('NULL','Zaaiviool','3','Heinenoord');
